name: tap_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-213.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^8.0.5
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  sensors_plus: ^3.0.2
  tcp_socket_connection: ^0.3.1
  bonsoir: ^2.2.0+1
  tflite_flutter: ^0.10.1
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  permission_handler: ^10.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/tap_app_logo.webp
    - lib/assets/models/model_combined_g.tflite
